title: Bruno Melício
description: AI Lecturer & Researcher
email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brunomelicio.com" # the base hostname & protocol for your site

theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to the
# internal default list.

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Enable support for HTML5-style sectioning elements in markdown
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false

# Permalinks
permalink: pretty

# Collections
collections:
  pages:
    output: true
    permalink: /:path/
